/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon May  1 14:35:55 2017. */

#include "usdata.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t USData_fields[4] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, USData, sensor_id, sensor_id, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, USData, timestamp, sensor_id, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, USData, reading, timestamp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
