.\" Manpage for serialvehicle
.\" Author: Jónatan Pétursson <jonatan.petur@gmail.com>.

.TH serialvehicle 1 "27 March 2017" "0.0.6" "scaledcars-example man page"

.SH NAME
serialvehicle \- Example software for scaled cars.



.SH SYNOPSIS
.B serialvehicle --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B scaledcars --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

