/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon May  1 14:35:55 2017. */

#ifndef PB_SENSORPACKAGE_PB_H_INCLUDED
#define PB_SENSORPACKAGE_PB_H_INCLUDED
#include "pb.h"
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
