/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon May  1 14:35:55 2017. */

#ifndef PB_USDATA_PB_H_INCLUDED
#define PB_USDATA_PB_H_INCLUDED
#include "pb.h"
/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _USData {
    bool has_sensor_id;
    int32_t sensor_id;
    bool has_timestamp;
    int32_t timestamp;
    bool has_reading;
    int32_t reading;
/* @@protoc_insertion_point(struct:USData) */
} USData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define USData_init_default                      {false, 0, false, 0, false, 0}
#define USData_init_zero                         {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define USData_sensor_id_tag                     1
#define USData_timestamp_tag                     2
#define USData_reading_tag                       3

/* Struct field encoding specification for nanopb */
extern const pb_field_t USData_fields[4];

/* Maximum encoded size of messages (where known) */
#define USData_size                              33

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define USDATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
