/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Apr 24 13:53:25 2017. */

#include "vehiclecontrol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t scaledcars_VehicleCommand_fields[7] = {
    PB_FIELD(  1, FIXED64 , OPTIONAL, STATIC  , FIRST, scaledcars_VehicleCommand, speed, speed, 0),
    PB_FIELD(  2, FIXED64 , OPTIONAL, STATIC  , OTHER, scaledcars_VehicleCommand, acceleration, speed, 0),
    PB_FIELD(  3, FIXED64 , OPTIONAL, STATIC  , OTHER, scaledcars_VehicleCommand, steeringWheelAngle, acceleration, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, scaledcars_VehicleCommand, brakeLights, steeringWheelAngle, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, scaledcars_VehicleCommand, flashingLightsLeft, brakeLights, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, scaledcars_VehicleCommand, flashingLightsRight, flashingLightsLeft, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
