# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehiclecontrol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehiclecontrol.proto',
  package='scaledcars',
  serialized_pb=_b('\n\x14vehiclecontrol.proto\x12\nscaledcars\"\x9f\x01\n\x0eVehicleCommand\x12\r\n\x05speed\x18\x01 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x01\x12\x1a\n\x12steeringWheelAngle\x18\x03 \x01(\x01\x12\x13\n\x0b\x62rakeLights\x18\x04 \x01(\x08\x12\x1a\n\x12\x66lashingLightsLeft\x18\x05 \x01(\x08\x12\x1b\n\x13\x66lashingLightsRight\x18\x06 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VEHICLECOMMAND = _descriptor.Descriptor(
  name='VehicleCommand',
  full_name='scaledcars.VehicleCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='scaledcars.VehicleCommand.speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='scaledcars.VehicleCommand.acceleration', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='steeringWheelAngle', full_name='scaledcars.VehicleCommand.steeringWheelAngle', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brakeLights', full_name='scaledcars.VehicleCommand.brakeLights', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flashingLightsLeft', full_name='scaledcars.VehicleCommand.flashingLightsLeft', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flashingLightsRight', full_name='scaledcars.VehicleCommand.flashingLightsRight', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['VehicleCommand'] = _VEHICLECOMMAND

VehicleCommand = _reflection.GeneratedProtocolMessageType('VehicleCommand', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLECOMMAND,
  __module__ = 'vehiclecontrol_pb2'
  # @@protoc_insertion_point(class_scope:scaledcars.VehicleCommand)
  ))
_sym_db.RegisterMessage(VehicleCommand)


# @@protoc_insertion_point(module_scope)
