/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Thu Apr 27 15:57:31 2017. */

#ifndef PB_SCALEDCARS_USDATA_PB_H_INCLUDED
#define PB_SCALEDCARS_USDATA_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _scaledcars_USData {
    bool has_sensor_id;
    int32_t sensor_id;
    bool has_timestamp;
    int32_t timestamp;
    bool has_reading;
    int32_t reading;
/* @@protoc_insertion_point(struct:scaledcars_USData) */
} scaledcars_USData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define scaledcars_USData_init_default           {false, 0, false, 0, false, 0}
#define scaledcars_USData_init_zero              {false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define scaledcars_USData_sensor_id_tag          1
#define scaledcars_USData_timestamp_tag          2
#define scaledcars_USData_reading_tag            3

/* Struct field encoding specification for nanopb */
extern const pb_field_t scaledcars_USData_fields[4];

/* Maximum encoded size of messages (where known) */
#define scaledcars_USData_size                   33

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define USDATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
