/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Thu Apr 27 15:57:31 2017. */

#include "usdata.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t scaledcars_USData_fields[4] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, scaledcars_USData, sensor_id, sensor_id, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, scaledcars_USData, timestamp, sensor_id, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, scaledcars_USData, reading, timestamp, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
