version: "2"

services:
        odsimcamera:
                build: .
                network_mode: "host"
                volumes:
                        - ${conf}:/opt/configuration
                        - /tmp/.X11-unix:/tmp/.X11-unix:ro
                environment:
                        - DISPLAY=${DISPLAY}
                ipc: host
                command: /opt/od4/bin/odsimcamera --freq=$FREQ --cid=111 --verbose=1 --ipc=host -e DISPLAY=$$DISPLAY
                depends_on: ['odsupercomponent']
                working_dir: "/opt/configuration"

