version: "2"

services:
        proxy-camera:
                build: .
                group_add:
                        - video
                depends_on:
                        - odsupercomponent
                devices:
                        - "/dev/video0:/dev/video0"
                user: odv
                network_mode: host
                ipc: host
                command: "/opt/opendlv.core/bin/opendlv-core-system-proxy-camera --cid=111 --freq=20"

