version: '2'

services:
        lanefollower:
                build: .
                network_mode: host
                ipc: host
                environment:
                        - DISPLAY=${DISPLAY}
                volumes:
                        - ${conf}:/opt/configuration
                command: /opt/opendlv.scaledcars/bin/lanefollower --freq=$FREQ --cid=111 --verbose=1 -e DISPLAY=$$DISPLAY
                working_dir: /opt/configuration
