version: '2'

services:
        odsupercomponent:
                build: .
                network_mode: "host"
                volumes:
                        - ${conf}:/opt/configuration
                command: /opt/od4/bin/odsupercomponent --freq=$FREQ --cid=111 --verbose=1
                working_dir: /opt/configuration
        odsimvehicle:
                build: .
                network_mode: "host"
                volumes:
                        - ${conf}:/opt/configuration
                environment:
                        - FREQ=10
                command: /opt/od4/bin/odsimvehicle --freq=$FREQ --cid=111 --verbose=0
                depends_on: ['odsupercomponent']
                working_dir: "/opt/configuration"
        odsimirus:
                build: .
                network_mode: "host"
                volumes:
                        - ${conf}:/opt/configuration
                command: /opt/od4/bin/odsimirus --freq=$FREQ --cid=111 --verbose=0
                depends_on: ['odsupercomponent']
                working_dir: /opt/configuration

        odcockpit:
                build: .
                network_mode: "host"
                volumes:
                        - ${conf}:/opt/configuration  
                        - /tmp/.X11-unix:/tmp/.X11-unix:ro
                        - ~/recordings:/opt/recordings 
                ipc: host
                user: odv
                environment:
                        - DISPLAY=${DISPLAY}
                command: /opt/od4/bin/odcockpit --freq=$FREQ --cid=111 --verbose=0 -e DISPLAY=$$DISPLAY
                depends_on: ['odsupercomponent']
                working_dir: "/opt/configuration"
